const actionTypes = {
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_REQUESTED: 'FETCH_PRODUCTS_REQUESTED',
    FETCH_PRODUCTS_ERROR: 'FETCH_PRODUCTS_ERROR',
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_REQUESTED: 'FETCH_PRODUCT_REQUESTED',
    FETCH_PRODUCT_ERROR: 'FETCH_PRODUCT_ERROR',
  };
  
  export default actionTypes;
  